#!/usr/bin/env python
import sys
import time
import pprint
import telepot
import random
import datetime
import json
import cv2
import urllib2
import numpy as np
import sys
import os
import argparse

from tinydb import TinyDB, Query

class commands:
    addmovie, addmusic, addtorrent, unknown= range(4)

def show_wishlist(chat_id, media_type):
    bot.sendMessage(chat_id, "This is the " + media_type + " wishlist:")
    wishlist = Query()
    rows = db.search(wishlist.type == media_type)
    message = ""
    for row in rows:
        message += row['name'] + "\n"
    bot.sendMessage(chat_id, message)

def add_to_wishlist(chat_id, media_type, values):
    for value in values.split("\n"):
        db.insert({'type': media_type, 'name': value})
    bot.sendMessage(chat_id, media_type + " succesfully added.")

def handle(msg):
    global current_command
    global db 
    global args
    content_type, chat_type, chat_id = telepot.glance(msg) 
    user_id=msg['from']['id']
    if user_id != args.user_id:
        bot.sendMessage(chat_id, "Go away stalker !!!")
        return
    if (content_type == 'text'):
        text    = msg['text']
        if text == '/addmovie':
            bot.sendMessage(chat_id, "Send me a movie you want to add to the wishlist")
            current_command = commands.addmovie
        elif text == '/addmusic':
            bot.sendMessage(chat_id, "Send me some music you want to add to the wishlist")
            current_command = commands.addmusic
        elif text == '/addtorrent':
            bot.sendMessage(chat_id, "Send me a torrent you want to add to the download queue")
            current_command = commands.addtorrent
        elif text == '/showmusic':
            show_wishlist(chat_id, 'music')
        elif text == '/showmovies':
            show_wishlist(chat_id, 'movie')
        elif current_command != commands.unknown: 
            if current_command == commands.addmovie:
                add_to_wishlist(chat_id, 'movie', text)
            elif current_command == commands.addmusic:
                add_to_wishlist(chat_id, 'music', text)
            current_command = commands.unknown

parser = argparse.ArgumentParser(description='Instagram bot for HAL operations.')
parser.add_argument("token", help="Telegram bot token string as generated by BotFather")
parser.add_argument("db_path", help="Directory to store the database db.json file")
parser.add_argument("user_id", help="Telegram user ID to restrict the bot", type=int)
parser.parse_args()
args = parser.parse_args()

# Getting the token from command-line is better than embedding it in code,
# because tokens are supposed to be kept secret.

db = TinyDB(args.db_path + '/db.json')

current_command = commands.unknown
bot = telepot.Bot(args.token)
bot.message_loop(handle)
print ('Listening ...')


# Keep the program running.
while 1:
	time.sleep(10)
